import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { AuthGuard } from './guard/auth.guard';

const routes: Routes = [
  { path: '', redirectTo: 'start', pathMatch: 'full' },
  { path: 'home', loadChildren: () => import('./home/home.module').then( m => m.HomePageModule)},
  { path: 'start', loadChildren: './pages/start/start.module#StartPageModule' },
  { path: 'cust-login', loadChildren: './pages/cust/cust-login/cust-login.module#CustLoginPageModule' },
  { path: 'cust-home', loadChildren: './pages/cust/cust-home/cust-home.module#CustHomePageModule' },
  { path: 'news', loadChildren: './pages/news/news.module#NewsPageModule' },
  { path: 'cust-register', loadChildren: './pages/cust/cust-register/cust-register.module#CustRegisterPageModule' },
  { path: 'reset-password', loadChildren: './pages/cust/reset-password/reset-password.module#ResetPasswordPageModule' },
  { path: 'prod-cat', loadChildren: './pages/cust/prod-cat/prod-cat.module#ProdCatPageModule' },
  { path: 'prod-brand', loadChildren: './pages/cust/prod-brand/prod-brand.module#ProdBrandPageModule' },
  { path: 'prod-list', loadChildren: './pages/cust/prod-list/prod-list.module#ProdListPageModule' },
  { path: 'prod-desc', loadChildren: './pages/cust/prod-desc/prod-desc.module#ProdDescPageModule' },
  { path: 'about', loadChildren: './pages/cust/about/about.module#AboutPageModule' },
  { path: 'service-status', loadChildren: './pages/cust/service-status/service-status.module#ServiceStatusPageModule' },
  { path: 'service-desc', loadChildren: './pages/cust/service-desc/service-desc.module#ServiceDescPageModule' },
  { path: 'cust-profile', loadChildren: './pages/cust/cust-profile/cust-profile.module#CustProfilePageModule' },
  { path: 'edit-profile', loadChildren: './pages/cust/edit-profile/edit-profile.module#EditProfilePageModule' },
  { path: 'tech-login', loadChildren: './pages/tech/tech-login/tech-login.module#TechLoginPageModule' },
  { path: 'tech-home', loadChildren: './pages/tech/tech-home/tech-home.module#TechHomePageModule' },
  { path: 'open-tickets', loadChildren: './pages/tech/open-tickets/open-tickets.module#OpenTicketsPageModule' },
  { path: 'ticket-detail', loadChildren: './pages/tech/ticket-detail/ticket-detail.module#TicketDetailPageModule' },
  { path: 'supply-estimate', loadChildren: './pages/tech/supply-estimate/supply-estimate.module#SupplyEstimatePageModule' },
  { path: 'cons-login', loadChildren: './pages/cons/cons-login/cons-login.module#ConsLoginPageModule' },
  { path: 'cons-home', loadChildren: './pages/cons/cons-home/cons-home.module#ConsHomePageModule' },
  { path: 'cons-profile', loadChildren: './pages/cons/cons-profile/cons-profile.module#ConsProfilePageModule' },
  { path: 'groceries', loadChildren: './pages/cust/spec-cat/groceries/groceries.module#GroceriesPageModule' },
  { path: 'cart', loadChildren: './pages/cust/cart/cart.module#CartPageModule' },
  { path: 'closed-tickets', loadChildren: './pages/tech/closed-tickets/closed-tickets.module#ClosedTicketsPageModule' },
  { path: 'edit-ticket', loadChildren: './pages/tech/edit-ticket/edit-ticket.module#EditTicketPageModule' },
  { path: 'closed-ticket-detail', loadChildren: './pages/tech/closed-ticket-detail/closed-ticket-detail.module#ClosedTicketDetailPageModule' },
  { path: 'prod-subcat', loadChildren: './pages/cust/prod-subcat/prod-subcat.module#ProdSubcatPageModule' },
  { path: 'prod-latest-arrivals', loadChildren: './pages/cust/prod-latest-arrivals/prod-latest-arrivals.module#ProdLatestArrivalsPageModule' },
  { path: 'view-asset', loadChildren: './pages/cust/view-asset/view-asset.module#ViewAssetPageModule' },
  { path: 'asset-info', loadChildren: './pages/cust/asset-info/asset-info.module#AssetInfoPageModule' },
  { path: 'add-asset', loadChildren: './pages/cust/add-asset/add-asset.module#AddAssetPageModule' },
  { path: 'cons-start', loadChildren: './pages/cons/cons-start/cons-start.module#ConsStartPageModule' },
  { path: 'prodcons-login', loadChildren: './pages/cons/prodcons-login/prodcons-login.module#ProdconsLoginPageModule' },
  { path: 'celeb', loadChildren: './pages/cust/spec-cat/celeb/celeb.module#CelebPageModule' },
  { path: 'ebike', loadChildren: './pages/cust/spec-cat/ebike/ebike.module#EbikePageModule' },
  { path: 'bikes-cycles', loadChildren: './pages/cust/spec-cat/bikes-cycles/bikes-cycles.module#BikesCyclesPageModule' },
  { path: 'pest-control', loadChildren: './pages/cust/spec-cat/pest-control/pest-control.module#PestControlPageModule' },
  { path: 'pest-control-second', loadChildren: './pages/cust/spec-cat/pest-control-second/pest-control-second.module#PestControlSecondPageModule' },
  { path: 'image-modal', loadChildren: './pages/cust/image-modal/image-modal.module#ImageModalPageModule' },
  { path: 'celeb-form', loadChildren: './pages/cust/spec-cat/celeb-form/celeb-form.module#CelebFormPageModule' },
  { path: 'other-services', loadChildren: './pages/cust/other-services/other-services.module#OtherServicesPageModule' },
  { path: 'trending', loadChildren: './pages/cust/spec-cat/trending/trending.module#TrendingPageModule' },
  { path: 'medical', loadChildren: './pages/cust/spec-cat/medical/medical.module#MedicalPageModule' },
  { path: 'family-card', loadChildren: './pages/cust/spec-cat/family-card/family-card.module#FamilyCardPageModule' },
  { path: 'remainders', loadChildren: './pages/cust/spec-cat/remainders/remainders.module#RemaindersPageModule' },
  { path: 'quick-buy', loadChildren: './pages/cust/quick-buy/quick-buy.module#QuickBuyPageModule' },
  { path: 'docs', loadChildren: './pages/cust/spec-cat/docs/docs.module#DocsPageModule' },
  { path: 'insurance', loadChildren: './pages/cust/spec-cat/insurance/insurance.module#InsurancePageModule' },
  { path: 'pooja', loadChildren: './pages/cust/spec-cat/pooja/pooja.module#PoojaPageModule' },
  { path: 'celeb-package', loadChildren: './pages/cust/spec-cat/celeb-package/celeb-package.module#CelebPackagePageModule' },
  { path: 'grocery-level2', loadChildren: './pages/cust/grocery/grocery-level2/grocery-level2.module#GroceryLevel2PageModule' },
  { path: 'grocery-filter', loadChildren: './pages/cust/grocery/grocery-filter/grocery-filter.module#GroceryFilterPageModule' },
  { path: 'grocery-filterlist', loadChildren: './pages/cust/grocery/grocery-filterlist/grocery-filterlist.module#GroceryFilterlistPageModule' },
  { path: 'grocery-desc', loadChildren: './pages/cust/grocery/grocery-desc/grocery-desc.module#GroceryDescPageModule' },
  { path: 'otp-form', loadChildren: './pages/cust/otp-form/otp-form.module#OtpFormPageModule' },
  { path: 'trending-issues', loadChildren: './pages/cust/spec-cat/trending-issues/trending-issues.module#TrendingIssuesPageModule' },
  { path: 'issue-list', loadChildren: './pages/cust/spec-cat/issue-list/issue-list.module#IssueListPageModule' },
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
